server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: uri
          username: \u7528\u6237\u540D
          password: \u5BC6\u7801
          default-label: \u5206\u652F
